#--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customeranalysis
GROUP BY gender;

#--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,purchase_amount
FROM customeranalysis
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) AS average_purchase FROM customeranalysis);


#-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating),2) AS avg_review_rating
FROM customeranalysis
GROUP BY item_purchased
ORDER BY avg_review_rating desc
LIMIT 5;

#--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,ROUND( AVG(purchase_amount),2) AS avg_purchase
FROM customeranalysis
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,COUNT(customer_id) AS total_customers, AVG(purchase_amount) AS avg_spend , SUM(purchase_amount) AS total_revenue
FROM customeranalysis
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

#--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
#(which products rely heavily on discounts to sell)
SELECT item_purchased, ROUND(100*SUM(CASE 1 WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customeranalysis
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
#customer segmentation

WITH customer_type AS(
SELECT previous_purchases, customer_id,
 CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customeranalysis
)
SELECT customer_segment, COUNT(*) AS "Num_of_customers"
FROM customer_type
GROUP BY customer_segment;


#--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS
(
SELECT
	category,item_purchased, COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(
		PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customeranalysis
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <=3;


#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customeranalysis
WHERE previous_purchases > 5
GROUP BY subscription_status;


#--Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customeranalysis
GROUP BY age_group
ORDER BY total_revenue DESC;

#--Q11. Which categories generate the highest revenue per customer?
SELECT category, ROUND(SUM(purchase_amount)/COUNT(DISTINCT(customer_id)),2) AS rev_per_customer,
	SUM(purchase_amount) AS total_rev
FROM customeranalysis
GROUP BY category
ORDER by rev_per_customer DESC;

#--Q12. Which season generates the highest sales for each category?

WITH seasonal_sales AS(
SELECT category, season, SUM(purchase_amount) AS total_sales,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY SUM(purchase_amount) DESC)
AS season_rank
FROM customeranalysis
GROUP BY category, season
)
SELECT category,season, total_sales 
FROM seasonal_sales
WHERE season_rank = 1;

#--Q13. Identify high-value customers based on total spending

WITH customer_spending AS(
SELECT customer_id, SUM(purchase_amount) AS total_spending
FROM customeranalysis
GROUP BY customer_id)
SELECT customer_id,total_spending,
	CASE WHEN total_spending >= 100 THEN 'High Value' 
		WHEN total_spending BETWEEN 50 AND 99 THEN 'Medium Value'
        ELSE 'Low Value' 
        END AS customer_segmt
FROM customer_spending
ORDER BY total_spending DESC;
        
#--Q14. What percentage of customers are repeat buyers?

SELECT 
	ROUND(
    100 * SUM(
    CASE WHEN previous_purchases > 1 THEN 1
    ELSE 0
    END
    )/COUNT(*),2) AS repeat_custperc
FROM customeranalysis;